INSERT INTO SHOPPING_LIST_ITEM (`NAME`, `DESCRIPTION`, `AMOUNT`) VALUES ('Eggs', '10-pack', 1);
INSERT INTO SHOPPING_LIST_ITEM (`NAME`, `DESCRIPTION`, `AMOUNT`) VALUES ('Potatoes', 'in kilograms', 2);
INSERT INTO SHOPPING_LIST_ITEM (`NAME`, `DESCRIPTION`, `AMOUNT`) VALUES ('Onion', 'red', 1);